[build]
  command = "npm run build"
  publish = ".svelte-kit/netlify"

[build.environment]
  NODE_VERSION = "20"

# Edge функции для поиска
[[edge_functions]]
  path = "/api/garden/search"
  function = "garden-search"
  
[[edge_functions]]
  path = "/api/garden/notes"
  function = "garden-notes" 