[build]
  command = "npm run build"
  publish = ".svelte-kit/netlify"
  # Устанавливаем функцию для обслуживания всех маршрутов
  functions = ".netlify/functions-internal"

[build.environment]
  NODE_VERSION = "20"
  # Включаем поддержку ESM в функциях Netlify
  NODE_OPTIONS = "--enable-source-maps"

# Edge функции для поиска
[[edge_functions]]
  path = "/api/garden/search"
  function = "garden-search"
  
[[edge_functions]]
  path = "/api/garden/notes"
  function = "garden-notes" 