[build]
  command = "npm run build"
  publish = ".svelte-kit/netlify"

[build.environment]
  NODE_VERSION = "20"

# Настройка редиректов, чтобы SvelteKit мог обрабатывать все маршруты
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/render"
  status = 200

# Настройка для поддержки SPA фолбэка
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Настройка заголовков
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; font-src 'self' data:; connect-src 'self'"

# Настройка для кэширования статики
[[headers]]
  for = "/_app/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Edge функции для поиска
[[edge_functions]]
  path = "/api/garden/search"
  function = "garden-search"
  
[[edge_functions]]
  path = "/api/garden/notes"
  function = "garden-notes" 